print('*Cadastro de cliente*')
cliente=input('Cliente: ')
end=input('End.: ')
bairro=input('Bairro: ')
cidade=input('Cidade: ')
estado=input('UF: ')
cep=input('CEP: ')
telefone1=input('Tel1: ')
telefone2=input('Tel2: ')
email=input('email: ')
print('Seu cliente é',cliente,'.')
print('Seu end é',end,'.')
print('Seu bairro é',bairro,'.')
print('Sua cidade é',cidade,'.')
print('Seu estado é',UF,'.')
print('Seu CEP é',cep,'.')
print('Seu telefone1 é',telefone1,'.')
print('Seu telefone2 é',telefone2,'.')
print('Seu email é',email,'.')
input('está certo?')
print('acertei em cheio')